blueprint:
  name: Adjust a slider to adjust zone volume
  description: Adjust a slider to adjust zone volume
  domain: automation
  input:
    actionTarget:
      selector:
        entity:
          domain: media_player
    actionTrigger: 
      selector:
        entity:
          domain: input_number
    actionVariable:

alias: Audio - Adjust Volume !input actionName
description: ''

trigger:
  - platform: state
    entity_id: !input actionTrigger

variables:
  actionTrigger: !input actionTrigger
  actionVariable: !input actionVariable

action:
  - service: mono_amp.set_zone
    data:
      {{ actionVariable }}: '{{ states(actionTrigger) | int }}'
    target:
      entity_id: !input actionTarget
mode: single
